apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      volumes:
      - name: hello-world
        configMap:
          name: hello-world
      containers:
      - name: helloworld
        image: burdz/helloworld
        imagePullPolicy: Always
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: helloworld
                key: container.port
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
