apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: burdz/helloworld
        imagePullPolicy: Always
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: helloworld
                key: container.port
        ports:
        - containerPort: 8080