apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-k8s
  namespace: ${ parameters.namespace }
  labels:
    source: demo-v2
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo-v2
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo-v2
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/burdz/hello-world-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: hello-world-k8s-config
