apiVersion: v1
kind: Service
metadata:
  name: hello-world-k8s
spec:
  type: LoadBalancer
  selector:
    source: demo-v2
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
